_name_: sashimi
unconditional: true
in_channels: 1
out_channels: 1
diffusion_step_embed_dim_in: 128
diffusion_step_embed_dim_mid: 512
diffusion_step_embed_dim_out: 512
unet: true
d_model: 64
n_layers: 6
pool: [4, 4]
expand: 2
ff: 2
L: ${dataset.segment_length} # Truncates infinite kernel to length of training inputs
