_name_: wavenet
unconditional: true
in_channels: 1
out_channels: 1
diffusion_step_embed_dim_in: 128
diffusion_step_embed_dim_mid: 512
diffusion_step_embed_dim_out: 512
res_channels: 256
skip_channels: 256
num_res_layers: 36
dilation_cycle: 12
