defaults:
  - _self_
  - experiment: sc09

train: # Not used in generate.py
  # stdout_dir: exp/ # directory to save stdout logs
  name: null # Name of experiment (prefix of experiment name)
  ckpt_iter: max
  iters_per_ckpt: 10000
  iters_per_logging: 100
  n_iters: 1000001
  learning_rate: 2e-4
  batch_size_per_gpu: 4
  n_samples: 16 # Samples per GPU to generate per checkpoint
  mel_path: null # Path to load spectrograms from for vocoding

generate: # Not used in train.py
  name: null # Name of experiment (prefix of experiment name)
  ckpt_iter: max # Which checkpoint to use; assign a number or "max"
  ckpt_smooth: -1 # Which checkpoint to start averaging from (experimental)
  n_samples: 16 # Number of utterances to be generated (per GPU)
  batch_size: null # Number of samples to generate at once per GPU. null means max (equal to samples_per_gpu)
  mel_path: null
  mel_name: null

distributed:
  dist_backend: nccl
  dist_url: tcp://localhost:54321

wandb:
  mode: disabled # Pass in 'wandb.mode=online' to turn on wandb logging
  project: hippo
  entity: null
  id: null # Set to string to resume logging from run
  job_type: training
